### ISSUE TITLE
aluminumScrap Bugs. 

### ISSUE THREAD

**Issue by jefmen908** [JZechy/satisfactory-manager#6]
aluminumScrap gives black screen. Change back to this name and evrything is fine. its not aluminiumScrap

**Comment by JZechy** [comment]
This problem came up with the Update 4, until then it was everything named as aluminium (which is also correct, british english), but they started using the american version. 

And I can't just easily rename the aliminium references in source codes as I can break someone's saved factory. So, there are possible bugs when references can be writedown as aluminum instread of aliminium.

Will take a closer look at everything about aluminium.

**Comment by jefmen908** [comment]
if i remove the cookies maby the problem solved. Will i lost the factory?

**Comment by jefmen908** [comment]
Cookies removed problem solved

**Comment by JZechy** [comment]
The application is not using cookies, but browser's local storage.

**Comment by JZechy** [comment]
I was checking application data about aluminum scrap and can't find any error here... When the application breaks after recipe select, it reffers to a data reference problem... 

I am now not sure what are you were reporting, can you please provide steps to reproduce?

**Comment by jefmen908** [comment]
i was putting in my aluminium factory and i closed it and the next day screen went black. 2 refinery one making ALt electrode - alu scrap. another one Sloppy alumina. 

Now i removed the coockies its solved.
